<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IS956AS" failures="2" tests="6" name="Test" time="31.873" errors="0" timestamp="2022-06-23T22:00:13 IST">
  <testcase classname="MerchantUI.LoginPage" name="CheckingForBrokenLink" time="12.445">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at MerchantUI.LoginPage.CheckingForBrokenLink(LoginPage.java:93)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- CheckingForBrokenLink -->
  <testcase classname="MerchantUI.LoginPage" name="loginFormTitleValidation" time="0.109"/>
  <testcase classname="MerchantUI.LoginPage" name="IsPartnerLogoDisplayed" time="0.058"/>
  <testcase classname="MerchantUI.LoginPage" name="ValidLoginAttempt" time="2.288"/>
  <testcase classname="MerchantUI.LoginPage" name="InvalidLoginAttempts" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NullPointerException">
      <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.lang.NullPointerException
at resources.XLUtils.getRowCount(XLUtils.java:29)
at MerchantUI.LoginPage.getInvalidTestData(LoginPage.java:164)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- InvalidLoginAttempts -->
  <testcase classname="MerchantUI.LoginPage" name="IsPCILogoDisplayed" time="0.046"/>
</testsuite> <!-- Test -->
